name = "Bdmeter Theme Template"
license = "MIT"
licenselink = "https://github.com/ronibd0/bdmeter.info/main/LICENSE"
description = "The Bdmeter blogsite web template"
homepage = "https://github.com/ronibd0/bdmeter.info"
demosite = "https://bdmeter.info/"
tags = [
    "business",
    "industry",
    "climate",
    "finance",
    "building-material",
    "meatal-industry",
    "textile",
    "environment",
    "information",
    "media",
    "technology",
    "research",
    "human-resource",
    "cosmetic-industry",
    "plastic-industry",
    "electronics",
    "oil-gas-industry",
    "future",
    "economy",
    "life-style",
    "health"
]
features = ["search", "flexible", "modular"]
[author]
name = "Bdmeter Framework Authors"
homepage = "https://bdmeter.info/"
